FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    'econ-ark @ git+https://github.com/econ-ark/HARK.git@ConsAggIndMarkovModel' \
    numpy \
    scipy \
    matplotlib \
    dill

WORKDIR /workspace
