#!/usr/bin/env bash
# Auto-generated by reproduce/build_manifest.py emit-recipe.
# Reproduces the run captured in:
#   comp_nano_20260426-2315.json
# Originally invoked as:
#   ./reproduce.sh --comp nano
# At: 2026-04-26T23:15:35Z
# By: econ-ark@ECON-MW-7MYCC14 on linux-x86_64
# Wall clock: 3.0 seconds.

set -euo pipefail

ANCHOR_COMMIT="3d5f90ff09306b94800dfe98bcaec8ee16669a61"
ANCHOR_BRANCH="bug034-035-cdc-consistency-cleanup"
ANCHOR_HARK_VERSION="0.17.1"

# 1. Verify worktree clean (refuse to replay onto a dirty tree).
if [[ -n "$(git status --porcelain)" ]]; then
    echo "Worktree dirty; refuse to replay (commit/stash first)." >&2
    exit 1
fi

# 2. Check out the recorded commit.
git fetch origin || true
git checkout "$ANCHOR_COMMIT"

# 3. Verify HARK version matches.
got_hark="$(python -c 'import HARK; print(HARK.__version__)' 2>/dev/null || true)"
if [[ "$got_hark" != "$ANCHOR_HARK_VERSION" ]]; then
    echo "HARK version mismatch: expected $ANCHOR_HARK_VERSION, got '$got_hark'" >&2
    echo "Re-sync env: bash reproduce/uv_sync_repair.sh" >&2
    exit 1
fi

# 4. Verify input-data hashes match.
for entry in \
    "70d6c8a258dfbfa36d458f45867c2370fbc29ecb216483b429243044c5c919ef:Code/HA-Models/Target_AggMPCX_LiquWealth/LiquWealth_Distribution_a.xlsx" \
    "72f4c7da3b5968bdfcf3201d28c857e20b5086ad7e8a325c63cf902c3b226afe:Code/HA-Models/Target_AggMPCX_LiquWealth/LiquWealth_Distribution_b.xlsx" \
    "38bfe8fd231b6e2b7db25c09b38c9d439ebe5ab7beee75cf1cb18e5e680c6e61:Code/HA-Models/Target_AggMPCX_LiquWealth/Data_AggMPC_LotteryWin.xlsx"; do
    expected="${entry%%:*}"
    path="${entry#*:}"
    got="$(shasum -a 256 "$path" | cut -d' ' -f1)"
    if [[ "$expected" != "$got" ]]; then
        echo "Input-data hash mismatch on $path" >&2
        echo "  expected: $expected" >&2
        echo "  got:      $got" >&2
        exit 1
    fi
done

# 5. Re-establish the original invocation's env vars.
# (no HAFISCAL_* env vars were set at the original invocation)

# 6. Replay the original command.
exec ./reproduce.sh --comp nano
