#!/usr/bin/env bash
# Retroactive reproduce-recipe for the MC welfare-6 anchor of 2026-04-21.
# Hand-assembled 2026-04-26 (NOT auto-generated by build_manifest.py).
#
# Reproduces the run captured in:
#   comp_full_20260421-1911_mc-only_retroactive.json
# Originally invoked as (per do_all.py:209 wrapper, with Steps 1-4 skipped):
#   python run_welfare6_parallel.py --baseline \
#       --out-dir welfare6_scenario_results_Baseline_reproduce \
#       --table-dir Tables/Baseline
# At: 2026-04-21T18:20:15Z (start) / 2026-04-21T19:11:18Z (end)
# By: econ-ark@ECON-MW-7MYCC14 on linux-x86_64
# Wall clock: 3131s (~52 min parallel; ~8.4 hours CPU-sum across 12 scenarios).

set -euo pipefail

ANCHOR_COMMIT="22cabc54e6f0bd7fc86b19f0f7b71f02389e741d"
ANCHOR_BRANCH="0.14.1-to-0.17.0-upgrade-validation_TM-vs-MC"
ANCHOR_HARK_VERSION="0.17.1"

# 1. Verify worktree clean (refuse to replay onto a dirty tree).
if [[ -n "$(git status --porcelain)" ]]; then
    echo "Worktree dirty; refuse to replay (commit/stash first)." >&2
    exit 1
fi

# 2. Check out the recorded run-time commit.
git fetch origin || true
git checkout "$ANCHOR_COMMIT"

# 3. Verify HARK version matches.
got_hark="$(python -c 'import HARK; print(HARK.__version__)' 2>/dev/null || true)"
if [[ "$got_hark" != "$ANCHOR_HARK_VERSION" ]]; then
    echo "HARK version mismatch: expected $ANCHOR_HARK_VERSION, got '$got_hark'" >&2
    echo "Re-sync env: bash reproduce/uv_sync_repair.sh" >&2
    exit 1
fi

# 4. Verify input-data hashes match.
for entry in \
    "70d6c8a258dfbfa36d458f45867c2370fbc29ecb216483b429243044c5c919ef:Code/HA-Models/Target_AggMPCX_LiquWealth/LiquWealth_Distribution_a.xlsx" \
    "72f4c7da3b5968bdfcf3201d28c857e20b5086ad7e8a325c63cf902c3b226afe:Code/HA-Models/Target_AggMPCX_LiquWealth/LiquWealth_Distribution_b.xlsx" \
    "38bfe8fd231b6e2b7db25c09b38c9d439ebe5ab7beee75cf1cb18e5e680c6e61:Code/HA-Models/Target_AggMPCX_LiquWealth/Data_AggMPC_LotteryWin.xlsx"; do
    expected="${entry%%:*}"
    path="${entry#*:}"
    got="$(shasum -a 256 "$path" | cut -d' ' -f1)"
    if [[ "$expected" != "$got" ]]; then
        echo "Input-data hash mismatch on $path" >&2
        echo "  expected: $expected" >&2
        echo "  got:      $got" >&2
        exit 1
    fi
done

# 5. Verify calibration file matches.
expected_cal="04c3e21878a08b37ed7b229162ab5dc99e4f8b68064207b983fa42750d3f097f"
got_cal="$(shasum -a 256 Code/HA-Models/Target_AggMPCX_LiquWealth/Result_AllTarget.txt | cut -d' ' -f1)"
if [[ "$expected_cal" != "$got_cal" ]]; then
    echo "Calibration hash mismatch on Result_AllTarget.txt" >&2
    echo "  expected: $expected_cal" >&2
    echo "  got:      $got_cal" >&2
    exit 1
fi

# 6. Replay the original command.
# (No HAFISCAL_* env vars need explicit setting; do_all.py wrapper sets STEP_1..4=0
#  but invoking run_welfare6_parallel.py directly sidesteps that gate entirely.)
cd Code/HA-Models/FromPandemicCode
exec python run_welfare6_parallel.py --baseline \
    --out-dir welfare6_scenario_results_Baseline_reproduce \
    --table-dir Tables/Baseline
